// AUTO GENERATED - DO NOT MODIFY
// ignore_for_file: type=lint
// coverage:ignore-file

part of 'generics.dart';

class _$UserImpl extends User {
  _$UserImpl({
    required this.id,
    required this.username,
  }) : super.ctor();

  @override
  final int id;

  @override
  final String username;

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is User &&
            runtimeType == other.runtimeType &&
            id == other.id &&
            username == other.username;
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
      id,
      username,
    ]);
  }

  @override
  String toString() {
    String toStringOutput = 'User{<optimized out>}';
    assert(() {
      toStringOutput = 'User@<$hexIdentity>{id: $id, username: $username}';
      return true;
    }());
    return toStringOutput;
  }

  @override
  Type get runtimeType => User;
}

class _$UserCopyWithProxy {
  _$UserCopyWithProxy(this._value);

  final User _value;

  @pragma('vm:prefer-inline')
  User id(int newValue) => this(id: newValue);

  @pragma('vm:prefer-inline')
  User username(String newValue) => this(username: newValue);

  @pragma('vm:prefer-inline')
  User call({
    final int? id,
    final String? username,
  }) {
    return _$UserImpl(
      id: id ?? _value.id,
      username: username ?? _value.username,
    );
  }
}

class $UserCopyWithProxyChain<$Result> {
  $UserCopyWithProxyChain(this._value, this._chain);

  final User _value;
  final $Result Function(User update) _chain;

  @pragma('vm:prefer-inline')
  $Result id(int newValue) => this(id: newValue);

  @pragma('vm:prefer-inline')
  $Result username(String newValue) => this(username: newValue);

  @pragma('vm:prefer-inline')
  $Result call({
    final int? id,
    final String? username,
  }) {
    return _chain(_$UserImpl(
      id: id ?? _value.id,
      username: username ?? _value.username,
    ));
  }
}

extension $UserExtension on User {
  _$UserCopyWithProxy get copyWith => _$UserCopyWithProxy(this);
}

class _$SuperUserImpl extends SuperUser {
  _$SuperUserImpl({
    required this.id,
    required this.username,
  }) : super.ctor();

  @override
  final int id;

  @override
  final String username;

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is SuperUser &&
            runtimeType == other.runtimeType &&
            id == other.id &&
            username == other.username;
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
      id,
      username,
    ]);
  }

  @override
  String toString() {
    String toStringOutput = 'SuperUser{<optimized out>}';
    assert(() {
      toStringOutput = 'SuperUser@<$hexIdentity>{id: $id, username: $username}';
      return true;
    }());
    return toStringOutput;
  }

  @override
  Type get runtimeType => SuperUser;
}

class _$SuperUserCopyWithProxy {
  _$SuperUserCopyWithProxy(this._value);

  final SuperUser _value;

  @pragma('vm:prefer-inline')
  SuperUser id(int newValue) => this(id: newValue);

  @pragma('vm:prefer-inline')
  SuperUser username(String newValue) => this(username: newValue);

  @pragma('vm:prefer-inline')
  SuperUser call({
    final int? id,
    final String? username,
  }) {
    return _$SuperUserImpl(
      id: id ?? _value.id,
      username: username ?? _value.username,
    );
  }
}

class $SuperUserCopyWithProxyChain<$Result> {
  $SuperUserCopyWithProxyChain(this._value, this._chain);

  final SuperUser _value;
  final $Result Function(SuperUser update) _chain;

  @pragma('vm:prefer-inline')
  $Result id(int newValue) => this(id: newValue);

  @pragma('vm:prefer-inline')
  $Result username(String newValue) => this(username: newValue);

  @pragma('vm:prefer-inline')
  $Result call({
    final int? id,
    final String? username,
  }) {
    return _chain(_$SuperUserImpl(
      id: id ?? _value.id,
      username: username ?? _value.username,
    ));
  }
}

extension $SuperUserExtension on SuperUser {
  _$SuperUserCopyWithProxy get copyWith => _$SuperUserCopyWithProxy(this);
}

extension $AsyncResult<T> on AsyncResult<T> {
  R when<R>({
    required R Function() loading,
    required R Function(AsyncResultData<T> value) data,
    required R Function(AsyncResultError<T> value) error,
  }) {
    if (this is AsyncResultLoading<T>) {
      return loading();
    }
    if (this is AsyncResultData<T>) {
      return data(this as AsyncResultData<T>);
    }
    if (this is AsyncResultError<T>) {
      return error(this as AsyncResultError<T>);
    }
    throw UnimplementedError('$runtimeType is not generated by this plugin');
  }

  R maybeWhen<R>({
    R Function()? loading,
    R Function(AsyncResultData<T> value)? data,
    R Function(AsyncResultError<T> value)? error,
    required R Function() orElse,
  }) {
    if (loading != null && this is AsyncResultLoading<T>) {
      return loading();
    }
    if (data != null && this is AsyncResultData<T>) {
      return data(this as AsyncResultData<T>);
    }
    if (error != null && this is AsyncResultError<T>) {
      return error(this as AsyncResultError<T>);
    }
    return orElse();
  }
}

class AsyncResultLoading<T> extends AsyncResult<T> {
  const AsyncResultLoading() : super._();

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
    ]);
  }

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is AsyncResultLoading<T> && runtimeType == other.runtimeType;
  }

  @override
  String toString() {
    String toStringOutput = 'AsyncResultLoading{<optimized out>}';
    assert(() {
      toStringOutput = 'AsyncResultLoading@<$hexIdentity>{}';
      return true;
    }());
    return toStringOutput;
  }
}

class AsyncResultData<T> extends AsyncResult<T> {
  AsyncResultData(
    this.data,
  ) : super._();

  final T data;

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
      data,
    ]);
  }

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is AsyncResultData<T> && runtimeType == other.runtimeType && data == other.data;
  }

  @override
  String toString() {
    String toStringOutput = 'AsyncResultData{<optimized out>}';
    assert(() {
      toStringOutput = 'AsyncResultData@<$hexIdentity>{data: $data}';
      return true;
    }());
    return toStringOutput;
  }
}

class AsyncResultError<T> extends AsyncResult<T> {
  AsyncResultError(
    this.error, {
    this.stackTrace,
  }) : super._();

  final Object error;

  final StackTrace? stackTrace;

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
      error,
      stackTrace,
    ]);
  }

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is AsyncResultError<T> &&
            runtimeType == other.runtimeType &&
            error == other.error &&
            stackTrace == other.stackTrace;
  }

  @override
  String toString() {
    String toStringOutput = 'AsyncResultError{<optimized out>}';
    assert(() {
      toStringOutput = 'AsyncResultError@<$hexIdentity>{error: $error, stackTrace: $stackTrace}';
      return true;
    }());
    return toStringOutput;
  }
}

extension $UnionWithGenericConstraints<T extends User> on UnionWithGenericConstraints<T> {
  R when<R>({
    required R Function(UnionWithGenericConstraintsData<T> value) data,
  }) {
    if (this is UnionWithGenericConstraintsData<T>) {
      return data(this as UnionWithGenericConstraintsData<T>);
    }
    throw UnimplementedError('$runtimeType is not generated by this plugin');
  }

  R maybeWhen<R>({
    R Function(UnionWithGenericConstraintsData<T> value)? data,
    required R Function() orElse,
  }) {
    if (data != null && this is UnionWithGenericConstraintsData<T>) {
      return data(this as UnionWithGenericConstraintsData<T>);
    }
    return orElse();
  }
}

class UnionWithGenericConstraintsData<T extends User> extends UnionWithGenericConstraints<T> {
  UnionWithGenericConstraintsData(
    this.data,
  ) : super._();

  final T data;

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
      data,
    ]);
  }

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is UnionWithGenericConstraintsData<T> &&
            runtimeType == other.runtimeType &&
            data == other.data;
  }

  @override
  String toString() {
    String toStringOutput = 'UnionWithGenericConstraintsData{<optimized out>}';
    assert(() {
      toStringOutput = 'UnionWithGenericConstraintsData@<$hexIdentity>{data: $data}';
      return true;
    }());
    return toStringOutput;
  }
}
