// AUTO GENERATED - DO NOT MODIFY

// ignore_for_file: library_private_types_in_public_api, unused_element, unused_field

part of 'exceptions.dart';

extension $DcpException on DcpException {
  R when<R>({
    required R Function() pubspecYamlNotFound,
    required R Function() requiresFileGenerationMode,
    required R Function() dartToolFolderNotFound,
    required R Function(DcpExceptionPackageNotFound value) packageNotFound,
  }) {
    if (this is DcpExceptionPubspecYamlNotFound) {
      return pubspecYamlNotFound();
    }
    if (this is DcpExceptionRequiresFileGenerationMode) {
      return requiresFileGenerationMode();
    }
    if (this is DcpExceptionDartToolFolderNotFound) {
      return dartToolFolderNotFound();
    }
    if (this is DcpExceptionPackageNotFound) {
      return packageNotFound(this as DcpExceptionPackageNotFound);
    }
    throw UnimplementedError('$runtimeType is not generated by this plugin');
  }

  R maybeWhen<R>({
    R Function()? pubspecYamlNotFound,
    R Function()? requiresFileGenerationMode,
    R Function()? dartToolFolderNotFound,
    R Function(DcpExceptionPackageNotFound value)? packageNotFound,
    required R Function() orElse,
  }) {
    if (pubspecYamlNotFound != null && this is DcpExceptionPubspecYamlNotFound) {
      return pubspecYamlNotFound();
    }
    if (requiresFileGenerationMode != null && this is DcpExceptionRequiresFileGenerationMode) {
      return requiresFileGenerationMode();
    }
    if (dartToolFolderNotFound != null && this is DcpExceptionDartToolFolderNotFound) {
      return dartToolFolderNotFound();
    }
    if (packageNotFound != null && this is DcpExceptionPackageNotFound) {
      return packageNotFound(this as DcpExceptionPackageNotFound);
    }
    return orElse();
  }
}

class DcpExceptionPubspecYamlNotFound extends DcpException {
  const DcpExceptionPubspecYamlNotFound() : super._();

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
    ]);
  }

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is DcpExceptionPubspecYamlNotFound && runtimeType == other.runtimeType;
  }
}

class DcpExceptionRequiresFileGenerationMode extends DcpException {
  const DcpExceptionRequiresFileGenerationMode() : super._();

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
    ]);
  }

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is DcpExceptionRequiresFileGenerationMode && runtimeType == other.runtimeType;
  }
}

class DcpExceptionDartToolFolderNotFound extends DcpException {
  const DcpExceptionDartToolFolderNotFound() : super._();

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
    ]);
  }

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is DcpExceptionDartToolFolderNotFound && runtimeType == other.runtimeType;
  }
}

class DcpExceptionPackageNotFound extends DcpException {
  DcpExceptionPackageNotFound({
    required this.packageName,
  }) : super._();

  final String packageName;

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      runtimeType,
      packageName,
    ]);
  }

  @override
  bool operator ==(Object? other) {
    return identical(this, other) ||
        other is DcpExceptionPackageNotFound &&
            runtimeType == other.runtimeType &&
            packageName == other.packageName;
  }
}
