part of 'utils.dart';

extension StringX on String {
  /// Removes trailing whitespaces and carriage return characters.
  String normalizeWhitespaces() {
    return replaceFirst(RegExp(r'\s$'), '').replaceAll('\r', '');
  }

  /// Returns a string formatted using [DartFormatter]
  ///
  /// This is a workaround for generated code by the contributors,
  /// as the generated code in test has always length of 80 characters.
  String dartFormat({int lineLength = 100}) {
    return DartFormatter(pageWidth: lineLength).format(this).normalizeWhitespaces();
  }
}

typedef ContributorConstructor = AssistContributor Function(String path);

extension InOutFilesList on List<InOutFilesPair> {
  /// Computes and returns the assists generated by the
  /// passed contributor for the the given file.
  Future<AssistCollectorTest> computeAssists({
    required final String path,
    required final ContributorConstructor contributor,
  }) async {
    final AnalysisContextCollection analysis = AnalysisContextCollection(
      includedPaths: <String>[path],
      resourceProvider: PhysicalResourceProvider.INSTANCE,
    );

    final AssistContributor assistContributor = contributor(path);
    final AssistCollectorTest collector = AssistCollectorTest();

    await assistContributor.computeAssists(
      DartAssistRequestTest(
        offset: 0,
        length: 1,
        resourceProvider: PhysicalResourceProvider.INSTANCE,
        result: await analysis.contexts[0].currentSession
            .getResolvedUnit(path)
            .then((SomeResolvedUnitResult value) => value as ResolvedUnitResult),
      ),
      collector,
    );

    return collector;
  }

  /// Runs contributor tests found in 'test_files' folder
  void runContributorTests({
    required final String contributorsPath,
    required final ContributorConstructor contributor,
  }) {
    for (final InOutFilesPair pair in this) {
      final String inPath = pair.input.path;
      final String outPath = pair.output.path;

      test('${path.basename(inPath)} -> ${path.basename(outPath)}', () async {
        final AssistCollectorTest collector = await computeAssists(
          path: inPath,
          contributor: contributor,
        );

        expect(collector.assists, hasLength(1));
        expect(
          io.File(outPath).readAsStringSync().normalizeWhitespaces(),
          equals(collector.firstReplacement.dartFormat()),
        );
      });
    }
  }
}
