name: Publish Package

on:
  release:
    types: [published]

jobs:
  validate-plugin:
    uses: ./.github/workflows/validate_plugin.yml
    with:
      working_directory: ./package

  release:
    needs: validate-plugin

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1.7.1
        with:
          sdk: "3.9.2"

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: Install pana
        run: dart pub global activate pana

      - name: Run pana
        run: pana --no-warning --exit-code-threshold 19 .

      - name: Publish --dry-run
        run: dart run ../github_scripts/dry_publish.dart

      - name: ⚙ Setup Pub Credentials
        run: |
          mkdir -p ~/.config/dart
          echo "${{secrets.PUBDEV}}" | base64 --decode >> ~/.config/dart/pub-credentials.json

      - name: 🚀 Publish Package
        run: dart pub publish -f
