name: Plugin Validation Workflow

on:
  workflow_call:
    inputs:
      analyze_directories:
        required: false
        type: string
        default: "lib test tools"
      concurrency:
        required: false
        type: number
        default: 4
      dart_sdk:
        required: false
        type: string
        default: "3.9.2"
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      working_directory:
        required: false
        type: string
        default: "./package"

jobs:
  build:
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    runs-on: ${{inputs.runs_on}}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1.7.1
        with:
          sdk: ${{inputs.dart_sdk}}

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: ✨ Check Formatting
        run: dart format --output none --set-exit-if-changed .

      - name: 🕵️ Analyze
        run: dart analyze --fatal-infos --fatal-warnings ${{inputs.analyze_directories}}

      - name: 🧪 Run Tests
        run: dart test -j ${{inputs.concurrency}} --color
